-- agentlens_schema_pg.sql
-- Agent-centric star for AgentLens on PostgreSQL.
-- Database: claude_db (shared with StockBot). Schema: agentlens (own namespace).
-- Idempotent: safe to run repeatedly. Uses IF NOT EXISTS.
--
-- Mirrors the SCHEMA constant in star/build_star.py (SQLite), with the
-- Postgres conversions documented in Stock/01 - System/postgres-access.md
-- §4 (dialect rules) and §5 (schema conversions).
--
-- To wipe and rebuild (destructive), use the DROP block at the top,
-- otherwise this DDL is safe on populated tables.
--
-- Apply with:
--   psql: \i agentlens/star/agentlens_schema_pg.sql
--   MCP:  postgres_claude:execute_sql (paste the file)
--   Py:   build_star_pg.py --apply-schema

SET search_path TO agentlens;

-- =====================================================================
-- Optional DESTRUCTIVE reset — uncomment only for full rebuild.
-- Order respects FK dependencies (facts -> bridges -> dims).
-- =====================================================================
-- DROP TABLE IF EXISTS agentlens.fact_agent_snapshot     CASCADE;
-- DROP TABLE IF EXISTS agentlens.fact_agent_consumption  CASCADE;
-- DROP TABLE IF EXISTS agentlens.bridge_agent_skill      CASCADE;
-- DROP TABLE IF EXISTS agentlens.bridge_agent_connector  CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_agent               CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_skill               CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_connector           CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_model               CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_metric              CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_date                CASCADE;

-- =====================================================================
-- Dimensions
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.dim_agent (
    agent_key       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud           TEXT     NOT NULL,
    native_agent_id TEXT     NOT NULL,
    agent_name      TEXT,
    agent_type      TEXT,
    description     TEXT,
    instructions    TEXT,
    config_hash     TEXT,
    status          TEXT,
    enabled         SMALLINT,
    publisher       TEXT,
    owner_id        TEXT,
    created         TEXT,
    last_modified   TEXT,
    UNIQUE (cloud, native_agent_id)
);
CREATE INDEX IF NOT EXISTS idx_dim_agent_config_hash
    ON agentlens.dim_agent (config_hash);

CREATE TABLE IF NOT EXISTS agentlens.dim_skill (
    skill_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name TEXT NOT NULL,
    UNIQUE (skill_name)
);

CREATE TABLE IF NOT EXISTS agentlens.bridge_agent_skill (
    agent_key INTEGER NOT NULL REFERENCES agentlens.dim_agent (agent_key) ON DELETE CASCADE,
    skill_key INTEGER NOT NULL REFERENCES agentlens.dim_skill (skill_key) ON DELETE CASCADE,
    PRIMARY KEY (agent_key, skill_key)
);

CREATE TABLE IF NOT EXISTS agentlens.dim_connector (
    connector_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_name TEXT NOT NULL,
    UNIQUE (connector_name)
);

CREATE TABLE IF NOT EXISTS agentlens.bridge_agent_connector (
    agent_key     INTEGER NOT NULL REFERENCES agentlens.dim_agent (agent_key) ON DELETE CASCADE,
    connector_key INTEGER NOT NULL REFERENCES agentlens.dim_connector (connector_key) ON DELETE CASCADE,
    PRIMARY KEY (agent_key, connector_key)
);

CREATE TABLE IF NOT EXISTS agentlens.dim_model (
    model_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud     TEXT NOT NULL,
    native_id TEXT NOT NULL,
    UNIQUE (cloud, native_id)
);

CREATE TABLE IF NOT EXISTS agentlens.dim_metric (
    metric_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud       TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    namespace   TEXT NOT NULL,
    UNIQUE (cloud, metric_name, namespace)
);

-- date_key is the natural key YYYYMMDD, no identity needed
CREATE TABLE IF NOT EXISTS agentlens.dim_date (
    date_key  INTEGER PRIMARY KEY,
    full_date TEXT    NOT NULL,
    year      INTEGER NOT NULL,
    month     INTEGER NOT NULL,
    day       INTEGER NOT NULL
);

-- =====================================================================
-- Facts
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_consumption (
    agent_key  INTEGER          NOT NULL REFERENCES agentlens.dim_agent  (agent_key),
    metric_key INTEGER          NOT NULL REFERENCES agentlens.dim_metric (metric_key),
    model_key  INTEGER          NOT NULL REFERENCES agentlens.dim_model  (model_key),
    date_key   INTEGER          NOT NULL REFERENCES agentlens.dim_date   (date_key),
    ts         TEXT             NOT NULL,
    value      DOUBLE PRECISION,
    attributed SMALLINT         NOT NULL,
    PRIMARY KEY (agent_key, metric_key, model_key, ts)
);
CREATE INDEX IF NOT EXISTS idx_fact_consumption_date
    ON agentlens.fact_agent_consumption (date_key);
CREATE INDEX IF NOT EXISTS idx_fact_consumption_agent
    ON agentlens.fact_agent_consumption (agent_key);

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_snapshot (
    agent_key   INTEGER          NOT NULL REFERENCES agentlens.dim_agent  (agent_key),
    metric_key  INTEGER          NOT NULL REFERENCES agentlens.dim_metric (metric_key),
    date_key    INTEGER          NOT NULL REFERENCES agentlens.dim_date   (date_key),
    value_sum   DOUBLE PRECISION,
    value_count INTEGER,
    PRIMARY KEY (agent_key, metric_key, date_key)
);
CREATE INDEX IF NOT EXISTS idx_fact_snapshot_date
    ON agentlens.fact_agent_snapshot (date_key);

-- =====================================================================
-- Cost (FOCUS-lite) -- 2026-07-08
--
-- Decision: fact SEPARADO de fact_agent_consumption. Motivos:
--   * Grano distinto: coste es (recurso, meter, dia); consumo es
--     (agente, metrica, modelo, ts).
--   * Unidades distintas: mezclar moneda con tokens/llamadas en el mismo
--     ``value`` rompe la semantica de agregacion del snapshot.
--   * FOCUS aporta columnas (meter, subscription, resource_group) que se
--     perderian aplastandolas en la dim de metricas.
-- agent_key es NULLABLE: la atribucion recurso->agente llegara cuando
-- exista el mapeo (los native_agent_id del catalogo Agent 365 no son ARM
-- resource ids). Mientras, el coste queda a grano recurso, consultable
-- por dia/suscripcion/meter en Power BI.
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.fact_resource_cost (
    cloud             TEXT             NOT NULL,           -- 'azure' | 'aws'
    resource_id       TEXT             NOT NULL,
    date_key          INTEGER          NOT NULL REFERENCES agentlens.dim_date (date_key),
    meter_name        TEXT             NOT NULL DEFAULT '',
    billed_cost       DOUBLE PRECISION,
    effective_cost    DOUBLE PRECISION,
    consumed_quantity DOUBLE PRECISION,
    consumed_unit     TEXT,
    meter_category    TEXT,
    currency          TEXT,
    subscription_id   TEXT,
    resource_group    TEXT,
    agent_key         INTEGER          REFERENCES agentlens.dim_agent (agent_key),
    PRIMARY KEY (cloud, resource_id, date_key, meter_name)
);
CREATE INDEX IF NOT EXISTS idx_fact_resource_cost_date
    ON agentlens.fact_resource_cost (date_key);

-- =====================================================================
-- ETL bookkeeping -- 2026-07-08
--
-- Watermark de carga a nivel de fichero: build_star_pg.py salta los
-- parquets ya cargados (los upserts hacen que recargar sea inocuo pero
-- O(historico); con esto la carga es O(nuevo)). --full-scan lo ignora;
-- --rebuild lo trunca junto al resto.
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.etl_load_log (
    file_path TEXT        PRIMARY KEY,     -- relativo a raw root, separador '/'
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_count INTEGER
);
