-- agentlens_schema_pg.sql
-- Agent-centric star for AgentLens on PostgreSQL.
-- Database: claude_db (shared with StockBot). Schema: agentlens (own namespace).
-- Idempotent: safe to run repeatedly. Uses IF NOT EXISTS.
--
-- Mirrors the SCHEMA constant in star/build_star.py (SQLite), with the
-- Postgres conversions documented in Stock/01 - System/postgres-access.md
-- §4 (dialect rules) and §5 (schema conversions).
--
-- To wipe and rebuild (destructive), use the DROP block at the top,
-- otherwise this DDL is safe on populated tables.
--
-- Apply with:
--   psql: \i agentlens/star/agentlens_schema_pg.sql
--   MCP:  postgres_claude:execute_sql (paste the file)
--   Py:   build_star_pg.py --apply-schema

SET search_path TO agentlens;

-- =====================================================================
-- Optional DESTRUCTIVE reset — uncomment only for full rebuild.
-- Order respects FK dependencies (facts -> bridges -> dims).
-- =====================================================================
-- DROP TABLE IF EXISTS agentlens.fact_agent_snapshot     CASCADE;
-- DROP TABLE IF EXISTS agentlens.fact_agent_consumption  CASCADE;
-- DROP TABLE IF EXISTS agentlens.bridge_agent_skill      CASCADE;
-- DROP TABLE IF EXISTS agentlens.bridge_agent_connector  CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_agent               CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_skill               CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_connector           CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_model               CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_metric              CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_date                CASCADE;

-- =====================================================================
-- Dimensions
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.dim_agent (
    agent_key       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud           TEXT     NOT NULL,
    native_agent_id TEXT     NOT NULL,
    agent_name      TEXT,
    agent_type      TEXT,
    description     TEXT,
    instructions    TEXT,
    config_hash     TEXT,
    status          TEXT,
    enabled         SMALLINT,
    publisher       TEXT,
    owner_id        TEXT,
    created         TEXT,
    last_modified   TEXT,
    UNIQUE (cloud, native_agent_id)
);
CREATE INDEX IF NOT EXISTS idx_dim_agent_config_hash
    ON agentlens.dim_agent (config_hash);

CREATE TABLE IF NOT EXISTS agentlens.dim_skill (
    skill_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name TEXT NOT NULL,
    UNIQUE (skill_name)
);

CREATE TABLE IF NOT EXISTS agentlens.bridge_agent_skill (
    agent_key INTEGER NOT NULL REFERENCES agentlens.dim_agent (agent_key) ON DELETE CASCADE,
    skill_key INTEGER NOT NULL REFERENCES agentlens.dim_skill (skill_key) ON DELETE CASCADE,
    PRIMARY KEY (agent_key, skill_key)
);

CREATE TABLE IF NOT EXISTS agentlens.dim_connector (
    connector_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_name TEXT NOT NULL,
    UNIQUE (connector_name)
);

CREATE TABLE IF NOT EXISTS agentlens.bridge_agent_connector (
    agent_key     INTEGER NOT NULL REFERENCES agentlens.dim_agent (agent_key) ON DELETE CASCADE,
    connector_key INTEGER NOT NULL REFERENCES agentlens.dim_connector (connector_key) ON DELETE CASCADE,
    PRIMARY KEY (agent_key, connector_key)
);

CREATE TABLE IF NOT EXISTS agentlens.dim_model (
    model_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud     TEXT NOT NULL,
    native_id TEXT NOT NULL,
    UNIQUE (cloud, native_id)
);

CREATE TABLE IF NOT EXISTS agentlens.dim_metric (
    metric_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud       TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    namespace   TEXT NOT NULL,
    UNIQUE (cloud, metric_name, namespace)
);

-- date_key is the natural key YYYYMMDD, no identity needed
CREATE TABLE IF NOT EXISTS agentlens.dim_date (
    date_key  INTEGER PRIMARY KEY,
    full_date TEXT    NOT NULL,
    year      INTEGER NOT NULL,
    month     INTEGER NOT NULL,
    day       INTEGER NOT NULL
);

-- =====================================================================
-- Facts
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_consumption (
    agent_key  INTEGER          NOT NULL REFERENCES agentlens.dim_agent  (agent_key),
    metric_key INTEGER          NOT NULL REFERENCES agentlens.dim_metric (metric_key),
    model_key  INTEGER          NOT NULL REFERENCES agentlens.dim_model  (model_key),
    date_key   INTEGER          NOT NULL REFERENCES agentlens.dim_date   (date_key),
    ts         TEXT             NOT NULL,
    value      DOUBLE PRECISION,
    attributed SMALLINT         NOT NULL,
    PRIMARY KEY (agent_key, metric_key, model_key, ts)
);
CREATE INDEX IF NOT EXISTS idx_fact_consumption_date
    ON agentlens.fact_agent_consumption (date_key);
CREATE INDEX IF NOT EXISTS idx_fact_consumption_agent
    ON agentlens.fact_agent_consumption (agent_key);

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_snapshot (
    agent_key   INTEGER          NOT NULL REFERENCES agentlens.dim_agent  (agent_key),
    metric_key  INTEGER          NOT NULL REFERENCES agentlens.dim_metric (metric_key),
    date_key    INTEGER          NOT NULL REFERENCES agentlens.dim_date   (date_key),
    value_sum   DOUBLE PRECISION,
    value_count INTEGER,
    PRIMARY KEY (agent_key, metric_key, date_key)
);
CREATE INDEX IF NOT EXISTS idx_fact_snapshot_date
    ON agentlens.fact_agent_snapshot (date_key);

-- =====================================================================
-- Cost (FOCUS-lite) -- 2026-07-08
--
-- Decision: fact SEPARADO de fact_agent_consumption. Motivos:
--   * Grano distinto: coste es (recurso, meter, dia); consumo es
--     (agente, metrica, modelo, ts).
--   * Unidades distintas: mezclar moneda con tokens/llamadas en el mismo
--     ``value`` rompe la semantica de agregacion del snapshot.
--   * FOCUS aporta columnas (meter, subscription, resource_group) que se
--     perderian aplastandolas en la dim de metricas.
-- agent_key es NULLABLE: la atribucion recurso->agente llegara cuando
-- exista el mapeo (los native_agent_id del catalogo Agent 365 no son ARM
-- resource ids). Mientras, el coste queda a grano recurso, consultable
-- por dia/suscripcion/meter en Power BI.
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.fact_resource_cost (
    cloud             TEXT             NOT NULL,           -- 'azure' | 'aws'
    resource_id       TEXT             NOT NULL,
    date_key          INTEGER          NOT NULL REFERENCES agentlens.dim_date (date_key),
    meter_name        TEXT             NOT NULL DEFAULT '',
    billed_cost       DOUBLE PRECISION,
    effective_cost    DOUBLE PRECISION,
    consumed_quantity DOUBLE PRECISION,
    consumed_unit     TEXT,
    meter_category    TEXT,
    currency          TEXT,
    subscription_id   TEXT,
    resource_group    TEXT,
    agent_key         INTEGER          REFERENCES agentlens.dim_agent (agent_key),
    PRIMARY KEY (cloud, resource_id, date_key, meter_name)
);
CREATE INDEX IF NOT EXISTS idx_fact_resource_cost_date
    ON agentlens.fact_resource_cost (date_key);

-- =====================================================================
-- ETL bookkeeping -- 2026-07-08
--
-- Watermark de carga a nivel de fichero: build_star_pg.py salta los
-- parquets ya cargados (los upserts hacen que recargar sea inocuo pero
-- O(historico); con esto la carga es O(nuevo)). --full-scan lo ignora;
-- --rebuild lo trunca junto al resto.
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.etl_load_log (
    file_path TEXT        PRIMARY KEY,     -- relativo a raw root, separador '/'
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_count INTEGER
);

-- =====================================================================
-- Identity resolution + span grain + consumption tiers (ADR-010) -- 2026-07-09
--
-- ADR-010 "Attribution as Tiered Resolution": la atribucion agente<->consumo
-- se resuelve en la capa AgentLens con nivel de confianza explicito, sobre
-- grano span preservado. fact_agent_consumption pasa a rollup derivado.
--   * fact_agent_traces: landing a grano trace x span (topologia + caller +
--     content_ref). Sirve observabilidad y seguridad; los rollups derivan de el.
--   * bridge_agent_identity: mapeo cross-namespace otel_agent_id <-> packageId
--     M365 <-> agent ARN. Materializa la mapping table de ADR-003. NO se trunca
--     en --rebuild (dato curado); queda fuera de _ALL_TABLES en el loader.
--   * resolution_tier (native|bridge|correlation|unattributed): cada consumidor
--     filtra por confianza. Solo native+bridge son elegibles para chargeback.
--   * cost_basis (metered|allocated): nunca facturar coste repartido como medido.
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_traces (
    trace_id        TEXT        NOT NULL,
    span_id         TEXT        NOT NULL,
    parent_span_id  TEXT,
    agent_key       INTEGER     REFERENCES agentlens.dim_agent (agent_key),
    model_key       INTEGER     REFERENCES agentlens.dim_model (model_key),
    date_key        INTEGER     REFERENCES agentlens.dim_date  (date_key),
    ts              TIMESTAMPTZ NOT NULL,
    operation_name  TEXT,            -- invoke_agent | chat | execute_tool | create_agent | text_completion
    span_kind       TEXT,            -- agent_run | model_call | tool_call | retrieval
    native_agent_id TEXT,            -- gen_ai.agent.id tal cual en el span (puede ser NULL)
    caller_id       TEXT,            -- UserAuthenticatedId (best-effort; null-by-nature en runs programaticos)
    status          TEXT,
    duration_ms     DOUBLE PRECISION,
    input_tokens    INTEGER,
    output_tokens   INTEGER,
    total_tokens    INTEGER,
    tool_name       TEXT,
    content_ref     TEXT,            -- puntero a AppGenAIContent (dato gobernado), no el contenido
    resolution_tier TEXT        NOT NULL DEFAULT 'unattributed',
    PRIMARY KEY (trace_id, span_id)
);
CREATE INDEX IF NOT EXISTS idx_fact_traces_agent ON agentlens.fact_agent_traces (agent_key);
CREATE INDEX IF NOT EXISTS idx_fact_traces_date  ON agentlens.fact_agent_traces (date_key);

CREATE TABLE IF NOT EXISTS agentlens.bridge_agent_identity (
    agent_key    INTEGER     NOT NULL REFERENCES agentlens.dim_agent (agent_key) ON DELETE CASCADE,
    id_namespace TEXT        NOT NULL,     -- foundry_otel | m365_package | bedrock_arn
    native_id    TEXT        NOT NULL,     -- otel id base (version ':N' recortada) / packageId / ARN
    source       TEXT        NOT NULL,     -- curated_production | m365_registry | name_match_bulk
    confidence   TEXT        NOT NULL DEFAULT 'curated',   -- curated | name_match
    valid_from   TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to     TIMESTAMPTZ,
    PRIMARY KEY (id_namespace, native_id)
);

-- Columnas anadidas a tablas preexistentes (idempotente en DBs pobladas):
ALTER TABLE agentlens.fact_agent_consumption
    ADD COLUMN IF NOT EXISTS resolution_tier TEXT NOT NULL DEFAULT 'unattributed';
ALTER TABLE agentlens.fact_resource_cost
    ADD COLUMN IF NOT EXISTS cost_basis TEXT NOT NULL DEFAULT 'metered';

-- =====================================================================
-- Vistas de consumo (ADR-010) -- 2026-07-09
-- =====================================================================

-- FinOps: coste-por-agente por reparto de cuota de tokens (marcado allocated).
-- La rama 'unallocated' anade el remanente diario que ningun agente absorbe
-- (dias sin tokens atribuidos, o resto por redondeo): agent_key NULL y
-- cost_basis 'unallocated', de modo que la suma de la vista cuadra EXACTA
-- con fact_resource_cost. chargeback_eligible = solo tiers native/bridge.
CREATE OR REPLACE VIEW agentlens.v_finops_agent_cost AS
WITH agent_day AS (
    SELECT t.agent_key, t.date_key,
           SUM(COALESCE(t.total_tokens,0)) AS tokens,
           COUNT(*) FILTER (WHERE t.operation_name='invoke_agent') AS invocations,
           bool_or(t.resolution_tier IN ('native','bridge')) AS chargeback_eligible
    FROM agentlens.fact_agent_traces t
    WHERE t.resolution_tier <> 'unattributed'
    GROUP BY t.agent_key, t.date_key
),
day_tokens AS (SELECT date_key, SUM(tokens) AS total_tokens FROM agent_day GROUP BY date_key),
day_cost AS (
    SELECT date_key, SUM(COALESCE(effective_cost, billed_cost, 0)) AS cost, MAX(currency) AS currency
    FROM agentlens.fact_resource_cost GROUP BY date_key
),
allocated AS (
    SELECT ad.agent_key, a.agent_name, ad.date_key, ad.tokens, ad.invocations,
           ad.chargeback_eligible, dt.total_tokens, dc.cost AS day_resource_cost, dc.currency,
           CASE WHEN dt.total_tokens > 0
                THEN ROUND(((ad.tokens::numeric / dt.total_tokens) * COALESCE(dc.cost,0))::numeric, 6)
                ELSE 0 END AS allocated_cost,
           'allocated'::text AS cost_basis
    FROM agent_day ad
    JOIN agentlens.dim_agent a ON a.agent_key = ad.agent_key
    JOIN day_tokens dt ON dt.date_key = ad.date_key
    LEFT JOIN day_cost dc ON dc.date_key = ad.date_key
)
SELECT * FROM allocated
UNION ALL
SELECT NULL::int AS agent_key, '(unallocated)' AS agent_name, dc.date_key,
       NULL::bigint AS tokens, NULL::bigint AS invocations,
       false AS chargeback_eligible, NULL::bigint AS total_tokens,
       dc.cost AS day_resource_cost, dc.currency,
       ROUND((dc.cost - COALESCE(al.sum_alloc, 0))::numeric, 6) AS allocated_cost,
       'unallocated'::text AS cost_basis
FROM day_cost dc
LEFT JOIN (
    SELECT date_key, SUM(allocated_cost) AS sum_alloc FROM allocated GROUP BY date_key
) al USING (date_key)
WHERE dc.cost - COALESCE(al.sum_alloc, 0) > 0.0000005;

-- =====================================================================
-- Purview audit lens (ADR-005) -- 2026-07-09
--
-- fact_agent_audit: grano EVENTO del feed Audit.General (Purview / O365
-- Management Activity). Es el plano de gobierno/usuario del star:
--   * Join directo audit<->catalogo: TargetPlatformAgentId ('T_...'/'P_...')
--     ES el packageId de Agent 365 = dim_agent.native_agent_id (cloud m365).
--     Sin bridge. Ids no catalogados (BuiltIn_*, OutlookDraft, agentes
--     borrados) van al centinela con el id/nombre crudos preservados en el
--     fact -- son senal de gobierno, no error.
--   * El feed de audit NUNCA crea filas en dim_agent: el catalogo es SSoT.
--   * dim_user (UPN): dimension usuario. Purview es la fuente autoritativa
--     de caller (ADR-010 addendum); las trazas solo tienen best-effort.
--   * Campos de gobierno: DLPEvaluationDeferred, GuardrailDetails,
--     SensitivityLabelId, dlp_matches/sensitivity_labels (JSON crudo,
--     NULL cuando vacio para que el reporting filtre barato).
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.dim_user (
    user_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upn      TEXT NOT NULL,
    UNIQUE (upn)
);

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_audit (
    record_id               TEXT        PRIMARY KEY,
    ts                      TIMESTAMPTZ NOT NULL,
    date_key                INTEGER     NOT NULL REFERENCES agentlens.dim_date  (date_key),
    agent_key               INTEGER     NOT NULL REFERENCES agentlens.dim_agent (agent_key),
    user_key                INTEGER     REFERENCES agentlens.dim_user (user_key),
    record_type             TEXT,       -- 261 CopilotInteraction | 407 InferenceCall | 334 | 363
    operation               TEXT,
    workload                TEXT,       -- Copilot | Agent365
    app_host                TEXT,       -- AppHost (261/334) o ChannelName (407)
    thread_id               TEXT,
    native_agent_id         TEXT,       -- TargetPlatformAgentId / AppIdentity crudo
    agent_name_raw          TEXT,       -- TargetAgentName tal cual en el evento
    platform_agent_type     TEXT,       -- InferenceCall: DeclarativeAgent | AzureAIFoundry
    error_type              TEXT,
    dlp_evaluation_deferred SMALLINT,
    dlp_matches             TEXT,       -- JSON; NULL cuando '[]'
    sensitivity_label_id    TEXT,
    sensitivity_labels      TEXT,       -- JSON; NULL cuando '[]'
    guardrail_details       TEXT,       -- JSON; NULL cuando '[]'
    resolution_tier         TEXT        NOT NULL DEFAULT 'unattributed'
);
CREATE INDEX IF NOT EXISTS idx_fact_audit_agent ON agentlens.fact_agent_audit (agent_key);
CREATE INDEX IF NOT EXISTS idx_fact_audit_date  ON agentlens.fact_agent_audit (date_key);
CREATE INDEX IF NOT EXISTS idx_fact_audit_user  ON agentlens.fact_agent_audit (user_key);

-- Seguridad: consumo sin atribuir = senal de gobierno (shadow / test / guid-only).
CREATE OR REPLACE VIEW agentlens.v_security_unregistered_consumption AS
SELECT split_part(COALESCE(t.native_agent_id,''), ':', 1) AS unresolved_agent_id,
       CASE
         WHEN t.native_agent_id IS NULL OR t.native_agent_id = '' THEN 'no_agent_id'
         WHEN t.native_agent_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-' THEN 'guid_only'
         ELSE 'named_unregistered'
       END AS signal_class,
       COUNT(*) AS spans, COUNT(DISTINCT t.trace_id) AS traces,
       SUM(COALESCE(t.total_tokens,0)) AS tokens,
       MIN(t.ts) AS first_seen, MAX(t.ts) AS last_seen
FROM agentlens.fact_agent_traces t
WHERE t.resolution_tier = 'unattributed'
GROUP BY 1, 2
ORDER BY tokens DESC;

-- =====================================================================
-- CAPA DE REPORTING (2026-07-10) -- contrato para Power BI
--
--   Vistas de solo lectura sobre el star; los facts no se tocan.
--   Diseno PBIX: importar v_cio_agent_scorecard como dimension agente
--   (excluye 'instructions' a proposito: tamano de modelo), dim_model,
--   dim_user y las vistas fact. Calendario DAX relacionado por
--   date_key (YYYYMMDD). Kit completo en agentlens/powerbi/.
--
--   * v_finops_cost_allocation: asignacion de coste por share de tokens
--     a grano (cloud, dia, agente, modelo). La cloud de matching es la
--     del MODELO (runtime que factura), NO la de dim_agent: el registro
--     Agent 365 es federado y los agentes Foundry viven como cloud
--     m365 en dim_agent. Linea 'unallocated' explicita por dia/cloud.
--   * v_usage_daily: audit Purview a grano (dia, agente, usuario,
--     record_type, tier). Proxy de uso M365 (getCopilotAgentUsage es
--     techo de plataforma).
--   * v_traces_daily: telemetria a grano (dia, agente, modelo, tier).
--     error_spans = status HTTP 4xx/5xx.
--   * v_finops_funnel_daily: funnel uso -> consumo -> coste por
--     (dia, cloud) para la pagina CFO.
--   * v_cio_agent_scorecard: 1 fila por agente de catalogo (excluye
--     centinelas) con redundancia (cluster por config_hash exacto),
--     uso (audit nativo + trazas native/bridge), coste asignado y tier
--     KEEP / REVIEW / DECOMMISSION_CANDIDATE. El tier es PROVISIONAL
--     mientras la ventana de audit sea corta (backfill Purview
--     pendiente, retencion 180 dias en Audit Standard).
--   * v_cio_dup_clusters: 1 fila por cluster de duplicados exactos.
-- =====================================================================

CREATE OR REPLACE VIEW agentlens.v_finops_cost_allocation AS
WITH grain AS (
    SELECT m.cloud,
           t.agent_key,
           t.model_key,
           t.date_key,
           sum(COALESCE(t.total_tokens, 0)) AS tokens,
           count(*) FILTER (WHERE t.operation_name = 'invoke_agent') AS invocations
    FROM agentlens.fact_agent_traces t
    JOIN agentlens.dim_model m ON m.model_key = t.model_key
    WHERE t.resolution_tier <> 'unattributed'
    GROUP BY m.cloud, t.agent_key, t.model_key, t.date_key
),
day_tokens AS (
    SELECT cloud, date_key, sum(tokens) AS total_tokens
    FROM grain
    GROUP BY cloud, date_key
),
day_cost AS (
    SELECT cloud, date_key,
           sum(COALESCE(effective_cost, billed_cost, 0)) AS cost,
           max(currency) AS currency
    FROM agentlens.fact_resource_cost
    GROUP BY cloud, date_key
),
allocated AS (
    SELECT g.cloud,
           g.date_key,
           g.agent_key,
           g.model_key,
           g.tokens,
           g.invocations,
           CASE WHEN dt.total_tokens > 0
                THEN round(((g.tokens::numeric / dt.total_tokens)::double precision * COALESCE(dc.cost, 0::double precision))::numeric, 6)
                ELSE 0::numeric
           END AS allocated_cost,
           dc.currency,
           'allocated'::text AS cost_basis
    FROM grain g
    JOIN day_tokens dt ON dt.cloud = g.cloud AND dt.date_key = g.date_key
    LEFT JOIN day_cost dc ON dc.cloud = g.cloud AND dc.date_key = g.date_key
)
SELECT cloud, date_key, agent_key, model_key, tokens, invocations,
       allocated_cost, currency, cost_basis
FROM allocated
UNION ALL
SELECT dc.cloud,
       dc.date_key,
       NULL::integer,
       NULL::integer,
       NULL::bigint,
       NULL::bigint,
       round((dc.cost - COALESCE(al.sum_alloc, 0::numeric)::double precision)::numeric, 6),
       dc.currency,
       'unallocated'::text
FROM day_cost dc
LEFT JOIN (
    SELECT cloud, date_key, sum(allocated_cost) AS sum_alloc
    FROM allocated
    GROUP BY cloud, date_key
) al ON al.cloud = dc.cloud AND al.date_key = dc.date_key
WHERE (dc.cost - COALESCE(al.sum_alloc, 0::numeric)::double precision) > 0.0000005::double precision;

CREATE OR REPLACE VIEW agentlens.v_usage_daily AS
SELECT date_key,
       agent_key,
       user_key,
       record_type,
       resolution_tier,
       count(*) AS events,
       count(*) FILTER (WHERE error_type IS NOT NULL AND error_type <> '') AS error_events,
       count(*) FILTER (WHERE dlp_evaluation_deferred = 1) AS dlp_deferred_events
FROM agentlens.fact_agent_audit
GROUP BY date_key, agent_key, user_key, record_type, resolution_tier;

CREATE OR REPLACE VIEW agentlens.v_traces_daily AS
SELECT t.date_key,
       t.agent_key,
       t.model_key,
       t.resolution_tier,
       count(*) AS spans,
       count(*) FILTER (WHERE t.operation_name = 'invoke_agent') AS invocations,
       count(*) FILTER (WHERE t.status ~ '^[45]') AS error_spans,
       sum(COALESCE(t.input_tokens, 0)) AS input_tokens,
       sum(COALESCE(t.output_tokens, 0)) AS output_tokens,
       sum(COALESCE(t.total_tokens, 0)) AS total_tokens,
       round(avg(t.duration_ms)::numeric, 2) AS avg_duration_ms
FROM agentlens.fact_agent_traces t
GROUP BY t.date_key, t.agent_key, t.model_key, t.resolution_tier;

CREATE OR REPLACE VIEW agentlens.v_finops_funnel_daily AS
WITH usage_d AS (
    SELECT date_key,
           'm365'::text AS cloud,
           count(*) AS audit_events,
           count(DISTINCT user_key) AS audit_users
    FROM agentlens.fact_agent_audit
    GROUP BY date_key
),
traces_d AS (
    SELECT t.date_key,
           a.cloud,
           count(*) FILTER (WHERE t.operation_name = 'invoke_agent') AS invocations,
           sum(COALESCE(t.total_tokens, 0)) AS tokens
    FROM agentlens.fact_agent_traces t
    JOIN agentlens.dim_agent a ON a.agent_key = t.agent_key
    GROUP BY t.date_key, a.cloud
),
cost_d AS (
    SELECT date_key,
           cloud,
           sum(COALESCE(effective_cost, billed_cost, 0)) AS resource_cost,
           max(currency) AS currency
    FROM agentlens.fact_resource_cost
    GROUP BY date_key, cloud
)
SELECT date_key,
       cloud,
       u.audit_events,
       u.audit_users,
       t.invocations,
       t.tokens,
       c.resource_cost,
       c.currency
FROM usage_d u
FULL JOIN traces_d t USING (date_key, cloud)
FULL JOIN cost_d c USING (date_key, cloud);

CREATE OR REPLACE VIEW agentlens.v_cio_agent_scorecard AS
WITH clusters AS (
    SELECT config_hash, count(*) AS cluster_size
    FROM agentlens.dim_agent
    WHERE config_hash IS NOT NULL AND config_hash <> ''
      AND native_agent_id <> '(unattributed)'
    GROUP BY config_hash
    HAVING count(*) > 1
),
audit_usage AS (
    SELECT agent_key,
           count(*) AS audit_events,
           count(DISTINCT user_key) AS distinct_users,
           max(ts) AS last_audit_ts
    FROM agentlens.fact_agent_audit
    WHERE resolution_tier = 'native'
    GROUP BY agent_key
),
trace_usage AS (
    SELECT agent_key,
           count(*) FILTER (WHERE operation_name = 'invoke_agent') AS invocations,
           sum(COALESCE(total_tokens, 0)) AS total_tokens,
           max(ts) AS last_trace_ts
    FROM agentlens.fact_agent_traces
    WHERE resolution_tier IN ('native', 'bridge')
    GROUP BY agent_key
),
alloc AS (
    SELECT agent_key, sum(allocated_cost) AS allocated_cost
    FROM agentlens.v_finops_cost_allocation
    WHERE cost_basis = 'allocated'
    GROUP BY agent_key
)
SELECT a.agent_key,
       a.cloud,
       a.native_agent_id,
       a.agent_name,
       a.agent_type,
       a.publisher,
       a.owner_id,
       a.status,
       a.enabled,
       a.config_hash,
       COALESCE(c.cluster_size, 1) AS cluster_size,
       (c.config_hash IS NOT NULL) AS in_dup_cluster,
       COALESCE(u.audit_events, 0) AS audit_events,
       COALESCE(u.distinct_users, 0) AS distinct_users,
       u.last_audit_ts,
       COALESCE(t.invocations, 0) AS invocations,
       COALESCE(t.total_tokens, 0) AS total_tokens,
       t.last_trace_ts,
       COALESCE(al.allocated_cost, 0) AS allocated_cost_eur,
       (u.agent_key IS NOT NULL OR t.agent_key IS NOT NULL) AS has_usage_signal,
       (COALESCE(u.distinct_users, 0) = 1) AS single_user,
       CASE
           WHEN u.agent_key IS NOT NULL OR t.agent_key IS NOT NULL THEN 'KEEP'
           WHEN c.config_hash IS NOT NULL THEN 'DECOMMISSION_CANDIDATE'
           ELSE 'REVIEW'
       END AS tier
FROM agentlens.dim_agent a
LEFT JOIN clusters c ON c.config_hash = a.config_hash
LEFT JOIN audit_usage u ON u.agent_key = a.agent_key
LEFT JOIN trace_usage t ON t.agent_key = a.agent_key
LEFT JOIN alloc al ON al.agent_key = a.agent_key
WHERE a.native_agent_id <> '(unattributed)';

CREATE OR REPLACE VIEW agentlens.v_cio_dup_clusters AS
SELECT s.config_hash,
       count(*) AS members,
       string_agg(DISTINCT s.agent_type, ', ') AS agent_types,
       min(s.agent_name) AS sample_name,
       count(*) FILTER (WHERE s.has_usage_signal) AS used_members,
       sum(s.audit_events) AS total_audit_events,
       sum(s.total_tokens) AS total_tokens,
       sum(s.allocated_cost_eur) AS allocated_cost_eur,
       left(max(a.instructions), 300) AS prompt_sample
FROM agentlens.v_cio_agent_scorecard s
JOIN agentlens.dim_agent a ON a.agent_key = s.agent_key
WHERE s.in_dup_cluster
GROUP BY s.config_hash;

-- ============ ADR-011: COSTE POR MÉTODO Y DRIVERS ============
-- Modelo de coste transparente por origen de agente (decisión ADR-011 del
-- orquestador AgentLens). Sustituye la asunción implícita de que todo coste
-- es "factura cloud prorrateada por tokens" (v_finops_cost_allocation, que
-- NO se modifica) por un modelo explícito: cada agente tiene un método de
-- coste según su cloud/tipo (cost_method_map), y cada método genérico se
-- calcula a partir de un driver con una tarifa vigente (cost_driver_rate).
--
-- Métodos soportados:
--   metered_allocated  -> coste de factura cloud (Azure/AWS) prorrateado por
--                         share de tokens de trazas atribuidas. Ver Bloque A.
--   credit_rated        -> coste de créditos Copilot (M365) rateado a EUR y
--                         repartido por share de eventos de auditoría. Ver
--                         Bloque B. Incluye entradas M365 "sin tipo".
--   license_amortized   -> coste de licencia Copilot amortizado semanalmente
--                         por nº de asientos con licencia. Ver Bloque C. No
--                         se reparte por agente (coste a nivel de tenant).
--   bundled_zero         -> coste ya incluido en la licencia M365 base
--                         (SharePoint, Toolkit, apps Teams/"Not Available");
--                         coste marginal cero, no emite filas en la vista
--                         unificada (solo aparece etiquetado en
--                         v_agent_cost_method).

-- ---------- 1. Tabla de configuración: método de coste por origen ----------
CREATE TABLE IF NOT EXISTS agentlens.cost_method_map (
    map_id              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cloud               TEXT NOT NULL,
    agent_type_pattern  TEXT NOT NULL,   -- patrón LIKE sobre dim_agent.agent_type;
                                          -- '__NULL__' es el centinela para agent_type IS NULL
    cost_method         TEXT NOT NULL,
    cost_driver          TEXT NOT NULL,
    priority             INTEGER NOT NULL DEFAULT 100,  -- menor gana
    notes                TEXT,
    UNIQUE (cloud, agent_type_pattern)
);

COMMENT ON TABLE agentlens.cost_method_map IS
    'ADR-011: mapea cloud + patrón de agent_type al método de coste (cost_method) '
    'y su driver (cost_driver). Consumida por v_agent_cost_method.';

-- Semillas: descubiertas contra dim_agent real (2026-07-31):
--   aws/gen_ai_agent(6), aws/NULL(1,centinela)
--   azure/NULL(1,centinela)
--   m365/AmazonBedrock(2), m365/Copilot Studio(508), m365/Databricks(6),
--   m365/Foundry(39), m365/Microsoft 365 Agents Toolkit(1),
--   m365/Microsoft 365 Copilot Agent Builder(1035), m365/Not Available(230),
--   m365/SharePoint(79), m365/NULL(1,centinela)
-- Cobertura: todo agent_type real casa con un patrón; se añade además un
-- fallback m365/% de baja prioridad (200) para tipos futuros no previstos.
INSERT INTO agentlens.cost_method_map
    (cloud, agent_type_pattern, cost_method, cost_driver, priority, notes)
VALUES
    ('aws',   '%',                                       'metered_allocated', 'tokens',       100, 'Factura cloud prorrateada por share de tokens de trazas atribuidas'),
    ('aws',   '__NULL__',                                'metered_allocated', 'tokens',        50, 'Centinela unattributed de aws: mismo método que el resto de aws (el método del cloud correspondiente)'),
    ('azure', '%',                                       'metered_allocated', 'tokens',       100, 'Factura cloud prorrateada por share de tokens de trazas atribuidas'),
    ('azure', '__NULL__',                                'metered_allocated', 'tokens',        50, 'Centinela unattributed de azure: mismo método que el resto de azure (el método del cloud correspondiente)'),
    ('m365',  'SharePoint',                               'bundled_zero',      'none',          50, 'Coste empaquetado en licencia M365, marginal cero'),
    ('m365',  'Microsoft 365 Agents Toolkit',              'bundled_zero',      'none',          50, 'Coste empaquetado en licencia M365, marginal cero'),
    ('m365',  'Not Available',                             'bundled_zero',      'none',          50, 'Coste empaquetado en licencia M365, marginal cero (tipo de agente no resuelto, típico de apps Teams)'),
    ('m365',  '%Teams%',                                    'bundled_zero',      'none',          50, 'Apps de Teams: coste empaquetado en licencia M365, marginal cero'),
    ('m365',  'Copilot Studio',                             'credit_rated',      'audit_events',  50, 'Consumo de créditos Copilot rateado y repartido por eventos de auditoría'),
    ('m365',  'Microsoft 365 Copilot Agent Builder',         'credit_rated',      'audit_events',  50, 'Consumo de créditos Copilot rateado y repartido por eventos de auditoría'),
    ('m365',  '%Declarative%',                               'credit_rated',      'audit_events',  50, 'Agente declarativo: consumo de créditos Copilot rateado y repartido por eventos de auditoría'),
    ('m365',  '__NULL__',                                    'credit_rated',      'audit_events',  50, 'Sin tipo resuelto (incluye centinela unattributed de m365): tratado como creditable audit-based'),
    ('m365',  'Foundry',                                     'metered_allocated', 'tokens',        50, 'Entrada federada del registro A365: el runtime factura en su cloud'),
    ('m365',  'Databricks',                                  'metered_allocated', 'tokens',        50, 'Entrada federada del registro A365: el runtime factura en su cloud'),
    ('m365',  '%Bedrock%',                                    'metered_allocated', 'tokens',        50, 'Entrada federada del registro A365 (AmazonBedrock): el runtime factura en su cloud'),
    ('m365',  '%',                                            'credit_rated',      'audit_events', 200, 'Fallback: tipo m365 no reconocido explícitamente, tratado como creditable audit-based')
ON CONFLICT (cloud, agent_type_pattern) DO NOTHING;

-- ---------- 2. Tabla de configuración: tarifas de los drivers ----------
CREATE TABLE IF NOT EXISTS agentlens.cost_driver_rate (
    rate_id       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    scope          TEXT,
    driver         TEXT,
    unit_rate      NUMERIC,
    currency       TEXT DEFAULT 'EUR',
    rate_quality    TEXT DEFAULT 'estimated',
    source          TEXT,
    valid_from      DATE,
    valid_to        DATE NULL,
    UNIQUE (scope, driver, valid_from)
);

COMMENT ON TABLE agentlens.cost_driver_rate IS
    'ADR-011: tarifas vigentes por (scope, driver) con vigencia temporal. '
    'Consumida por v_finops_agent_cost_unified para los métodos credit_rated '
    'y license_amortized.';

INSERT INTO agentlens.cost_driver_rate
    (scope, driver, unit_rate, currency, rate_quality, source, valid_from, valid_to)
VALUES
    ('m365', 'credit',              0.008684, 'EUR', 'estimated', 'PAYG $0.01/crédito × fx 0.868405 xe.com 31-jul-2026; pendiente confirmar política PAYG con Microsoft', '2026-01-01', NULL),
    ('m365', 'credit_pack',         0.006947, 'EUR', 'estimated', 'Pack $200/25.000 créditos × fx; tarifa alternativa NO usada por la vista', '2026-01-01', NULL),
    ('m365', 'copilot_seat_month', 26.05,     'EUR', 'estimated', '$30/usuario/mes Enterprise × fx 0.868405', '2026-01-01', NULL),
    ('fx',   'usd_eur',             0.868405, 'EUR', 'estimated', 'xe.com mid-market 31-jul-2026', '2026-01-01', NULL)
ON CONFLICT (scope, driver, valid_from) DO NOTHING;

-- ---------- 3. Vista: método de coste resuelto por agente ----------
-- Cada agente de dim_agent (incluidos los 3 centinelas unattributed) resuelve
-- a exactamente un método, eligiendo el patrón de menor priority que casa
-- con su cloud + agent_type (LATERAL + LIMIT 1). Cobertura obligatoria: 0
-- agentes sin método (ver smoke test).
CREATE OR REPLACE VIEW agentlens.v_agent_cost_method AS
SELECT a.agent_key,
       a.cloud,
       a.agent_type,
       m.cost_method,
       m.cost_driver
FROM agentlens.dim_agent a
JOIN LATERAL (
    SELECT cm.cost_method, cm.cost_driver
    FROM agentlens.cost_method_map cm
    WHERE cm.cloud = a.cloud
      AND (
            (a.agent_type IS NOT NULL AND a.agent_type LIKE cm.agent_type_pattern)
         OR (a.agent_type IS NULL AND cm.agent_type_pattern = '__NULL__')
          )
    ORDER BY cm.priority ASC, cm.map_id ASC
    LIMIT 1
) m ON TRUE;

COMMENT ON VIEW agentlens.v_agent_cost_method IS
    'ADR-011: método y driver de coste resuelto para cada agente de dim_agent.';

-- ---------- 4. Vista: coste FinOps unificado por método y driver ----------
-- UNION ALL de tres bloques de cálculo genérico por driver. bundled_zero no
-- emite filas (coste marginal cero, ya etiquetado en v_agent_cost_method).
-- [Fix validación independiente 2026-07-31, ver puntos 1-3 abajo]
CREATE OR REPLACE VIEW agentlens.v_finops_agent_cost_unified AS
WITH
-- Bloque A: metered_allocated, a partir de v_finops_cost_allocation (NO se
-- modifica esa vista). Grano diario, agregado a (date_key, cloud, agent_key)
-- sumando sobre model_key (el detalle por modelo sigue disponible en
-- v_finops_cost_allocation). Incluye tanto filas asignadas a agente como el
-- remanente 'unallocated' a nivel de cloud (agent_key NULL).
block_a AS (
    SELECT v.date_key,
           v.cloud,
           v.agent_key,
           'metered_allocated'::text AS cost_method,
           'tokens'::text            AS cost_driver,
           sum(v.tokens)::numeric    AS driver_qty,
           NULL::numeric             AS unit_rate,
           sum(v.allocated_cost)     AS allocated_cost,
           max(v.currency)           AS currency,
           CASE WHEN v.cost_basis = 'allocated' THEN 'billed_allocated'
                ELSE 'billed_unallocated' END AS cost_quality,
           'day'::text AS period_grain
    FROM agentlens.v_finops_cost_allocation v
    GROUP BY v.date_key, v.cloud, v.agent_key, v.cost_basis
),
-- Bloque B: credit_rated, grano semanal. Semanas = fact_copilot_credits.date_key
-- (inicio de semana). El pool semanal de créditos se PARTE por
-- is_copilot_licensed (los créditos y las licencias no son aditivos: parte
-- del consumo de créditos ya está cubierto por el asiento Copilot):
--   - créditos de personas NO licenciadas (PAYG, facturable, aditivo):
--     se reparten por share de eventos de fact_agent_audit dentro de
--     [semana, semana+6] entre agentes ELEGIBLES (cost_method='credit_rated'
--     en v_agent_cost_method, excluyendo el centinela unattributed). Los
--     eventos de agentes NO elegibles (bundled_zero, metered_allocated
--     federado) y del centinela siguen contando en el denominador (total de
--     eventos de la semana) pero no en el numerador: su share "engorda" la
--     fila 'rated_payg_unallocated', no desaparece. cost_quality:
--     'rated_payg_allocated' / 'rated_payg_unallocated'.
--   - créditos de personas licenciadas: coste sombra ya cubierto por la
--     licencia (NO aditivo, memo), UNA fila semanal agent_key NULL,
--     cost_quality='rated_included', cost_driver='credits'.
weeks_rated AS (
    SELECT c.date_key                                                                        AS week_date_key,
           to_date(c.date_key::text, 'YYYYMMDD')                                              AS week_start,
           COALESCE(sum(c.total_credits_used) FILTER (WHERE NOT COALESCE(c.is_copilot_licensed, false)), 0) AS week_credits_payg,
           COALESCE(sum(c.total_credits_used) FILTER (WHERE c.is_copilot_licensed), 0)        AS week_credits_included,
           r.unit_rate                                                                        AS credit_rate
    FROM agentlens.fact_copilot_credits c
    JOIN agentlens.cost_driver_rate r
      ON r.scope = 'm365' AND r.driver = 'credit'
     AND r.valid_from <= to_date(c.date_key::text, 'YYYYMMDD')
     AND to_date(c.date_key::text, 'YYYYMMDD') < COALESCE(r.valid_to, 'infinity'::date)
    GROUP BY c.date_key, r.unit_rate
),
audit_events AS (
    SELECT to_date(fa.date_key::text, 'YYYYMMDD') AS event_date,
           fa.agent_key
    FROM agentlens.fact_agent_audit fa
    WHERE fa.agent_key IS NOT NULL
),
week_events AS (
    -- total de eventos de la semana, incluye centinela y agentes no
    -- elegibles (para que su share "engorde" el pool unallocated)
    SELECT w.week_date_key,
           count(ae.agent_key) AS total_events
    FROM weeks_rated w
    LEFT JOIN audit_events ae
      ON ae.event_date BETWEEN w.week_start AND w.week_start + 6
    GROUP BY w.week_date_key
),
agent_week_events AS (
    -- eventos por agente ELEGIBLE (cost_method='credit_rated' y NO
    -- centinela) dentro de la semana
    SELECT w.week_date_key,
           ae.agent_key,
           count(*) AS agent_events
    FROM weeks_rated w
    JOIN audit_events ae
      ON ae.event_date BETWEEN w.week_start AND w.week_start + 6
    JOIN agentlens.v_agent_cost_method m
      ON m.agent_key = ae.agent_key AND m.cost_method = 'credit_rated'
    WHERE ae.agent_key NOT IN (
        SELECT agent_key FROM agentlens.dim_agent WHERE native_agent_id = '(unattributed)'
    )
    GROUP BY w.week_date_key, ae.agent_key
),
agent_alloc AS (
    SELECT w.week_date_key,
           aw.agent_key,
           aw.agent_events,
           w.credit_rate,
           round((w.week_credits_payg * w.credit_rate * aw.agent_events::numeric / NULLIF(we.total_events, 0))::numeric, 6) AS agent_cost
    FROM weeks_rated w
    JOIN week_events we ON we.week_date_key = w.week_date_key
    JOIN agent_week_events aw ON aw.week_date_key = w.week_date_key
    WHERE we.total_events > 0
),
week_summary AS (
    SELECT w.week_date_key,
           w.week_credits_payg,
           w.credit_rate,
           (w.week_credits_payg * w.credit_rate) AS week_cost_payg,
           COALESCE(sum(aa.agent_cost), 0)       AS assigned_cost
    FROM weeks_rated w
    LEFT JOIN agent_alloc aa ON aa.week_date_key = w.week_date_key
    GROUP BY w.week_date_key, w.week_credits_payg, w.credit_rate
),
block_b_allocated AS (
    SELECT week_date_key AS date_key,
           'm365'::text  AS cloud,
           agent_key,
           'credit_rated'::text AS cost_method,
           'audit_events'::text AS cost_driver,
           agent_events::numeric AS driver_qty,
           credit_rate AS unit_rate,
           agent_cost AS allocated_cost,
           'EUR'::text AS currency,
           'rated_payg_allocated'::text AS cost_quality,
           'week'::text AS period_grain
    FROM agent_alloc
),
block_b_unallocated AS (
    -- resto del pool PAYG: share de eventos del centinela + agentes no
    -- elegibles (bundled_zero, metered_allocated federado) + semanas sin
    -- eventos. driver_qty = créditos PAYG sin asignar (equivalente
    -- algebraico de (week_cost_payg - assigned_cost) / credit_rate, exacto
    -- incluso sin eventos).
    SELECT week_date_key AS date_key,
           'm365'::text  AS cloud,
           NULL::integer AS agent_key,
           'credit_rated'::text AS cost_method,
           'audit_events'::text AS cost_driver,
           (week_credits_payg - (assigned_cost / credit_rate)) AS driver_qty,
           credit_rate AS unit_rate,
           (week_cost_payg - assigned_cost) AS allocated_cost,
           'EUR'::text AS currency,
           'rated_payg_unallocated'::text AS cost_quality,
           'week'::text AS period_grain
    FROM week_summary
),
block_b_included AS (
    -- pool cubierto por licencia (memo, NO aditivo): una fila por semana,
    -- sin repartir por agente ni por eventos.
    SELECT week_date_key AS date_key,
           'm365'::text  AS cloud,
           NULL::integer AS agent_key,
           'credit_rated'::text AS cost_method,
           'credits'::text AS cost_driver,
           week_credits_included AS driver_qty,
           credit_rate AS unit_rate,
           (week_credits_included * credit_rate) AS allocated_cost,
           'EUR'::text AS currency,
           'rated_included'::text AS cost_quality,
           'week'::text AS period_grain
    FROM weeks_rated
),
-- Bloque C: license_amortized, grano semanal, coste a nivel de tenant (no se
-- reparte por agente). seats = personas con licencia Copilot activa esa
-- semana; coste = seats × tarifa copilot_seat_month semanalizada (12/52.18).
block_c AS (
    SELECT c.date_key AS date_key,
           'm365'::text AS cloud,
           NULL::integer AS agent_key,
           'license_amortized'::text AS cost_method,
           'seats'::text AS cost_driver,
           count(DISTINCT c.person_id) FILTER (WHERE c.is_copilot_licensed)::numeric AS driver_qty,
           r.unit_rate AS unit_rate,
           round((count(DISTINCT c.person_id) FILTER (WHERE c.is_copilot_licensed)::numeric * r.unit_rate * 12.0 / 52.18)::numeric, 6) AS allocated_cost,
           'EUR'::text AS currency,
           'estimated'::text AS cost_quality,
           'week'::text AS period_grain
    FROM agentlens.fact_copilot_credits c
    JOIN agentlens.cost_driver_rate r
      ON r.scope = 'm365' AND r.driver = 'copilot_seat_month'
     AND r.valid_from <= to_date(c.date_key::text, 'YYYYMMDD')
     AND to_date(c.date_key::text, 'YYYYMMDD') < COALESCE(r.valid_to, 'infinity'::date)
    GROUP BY c.date_key, r.unit_rate
)
SELECT * FROM block_a
UNION ALL
SELECT * FROM block_b_allocated
UNION ALL
SELECT * FROM block_b_unallocated
UNION ALL
SELECT * FROM block_b_included
UNION ALL
SELECT * FROM block_c;

COMMENT ON VIEW agentlens.v_finops_agent_cost_unified IS
    'ADR-011: coste FinOps unificado por método/driver (metered_allocated diario '
    'desde v_finops_cost_allocation agregado por model_key, credit_rated '
    '(PAYG repartido por eventos entre agentes elegibles + memo included por '
    'licencia) y license_amortized semanales desde fact_copilot_credits/'
    'fact_agent_audit). bundled_zero no emite filas. '
    'total aditivo = billed_* + rated_payg* + license_amortized; '
    'rated_included es memo no aditivo.';
