-- agentlens_schema_pg.sql
-- Agent-centric star for AgentLens on PostgreSQL.
-- Database: claude_db (shared with StockBot). Schema: agentlens (own namespace).
-- Idempotent: safe to run repeatedly. Uses IF NOT EXISTS.
--
-- Mirrors the SCHEMA constant in star/build_star.py (SQLite), with the
-- Postgres conversions documented in Stock/01 - System/postgres-access.md
-- §4 (dialect rules) and §5 (schema conversions).
--
-- To wipe and rebuild (destructive), use the DROP block at the top,
-- otherwise this DDL is safe on populated tables.
--
-- Apply with:
--   psql: \i agentlens/star/agentlens_schema_pg.sql
--   MCP:  postgres_claude:execute_sql (paste the file)
--   Py:   build_star_pg.py --apply-schema

SET search_path TO agentlens;

-- =====================================================================
-- Optional DESTRUCTIVE reset — uncomment only for full rebuild.
-- Order respects FK dependencies (facts -> bridges -> dims).
-- =====================================================================
-- DROP TABLE IF EXISTS agentlens.fact_agent_snapshot     CASCADE;
-- DROP TABLE IF EXISTS agentlens.fact_agent_consumption  CASCADE;
-- DROP TABLE IF EXISTS agentlens.bridge_agent_skill      CASCADE;
-- DROP TABLE IF EXISTS agentlens.bridge_agent_connector  CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_agent               CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_skill               CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_connector           CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_model               CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_metric              CASCADE;
-- DROP TABLE IF EXISTS agentlens.dim_date                CASCADE;

-- =====================================================================
-- Dimensions
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.dim_agent (
    agent_key       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud           TEXT     NOT NULL,
    native_agent_id TEXT     NOT NULL,
    agent_name      TEXT,
    agent_type      TEXT,
    description     TEXT,
    instructions    TEXT,
    config_hash     TEXT,
    status          TEXT,
    enabled         SMALLINT,
    publisher       TEXT,
    owner_id        TEXT,
    created         TEXT,
    last_modified   TEXT,
    UNIQUE (cloud, native_agent_id)
);
CREATE INDEX IF NOT EXISTS idx_dim_agent_config_hash
    ON agentlens.dim_agent (config_hash);

CREATE TABLE IF NOT EXISTS agentlens.dim_skill (
    skill_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name TEXT NOT NULL,
    UNIQUE (skill_name)
);

CREATE TABLE IF NOT EXISTS agentlens.bridge_agent_skill (
    agent_key INTEGER NOT NULL REFERENCES agentlens.dim_agent (agent_key) ON DELETE CASCADE,
    skill_key INTEGER NOT NULL REFERENCES agentlens.dim_skill (skill_key) ON DELETE CASCADE,
    PRIMARY KEY (agent_key, skill_key)
);

CREATE TABLE IF NOT EXISTS agentlens.dim_connector (
    connector_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_name TEXT NOT NULL,
    UNIQUE (connector_name)
);

CREATE TABLE IF NOT EXISTS agentlens.bridge_agent_connector (
    agent_key     INTEGER NOT NULL REFERENCES agentlens.dim_agent (agent_key) ON DELETE CASCADE,
    connector_key INTEGER NOT NULL REFERENCES agentlens.dim_connector (connector_key) ON DELETE CASCADE,
    PRIMARY KEY (agent_key, connector_key)
);

CREATE TABLE IF NOT EXISTS agentlens.dim_model (
    model_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud     TEXT NOT NULL,
    native_id TEXT NOT NULL,
    UNIQUE (cloud, native_id)
);

CREATE TABLE IF NOT EXISTS agentlens.dim_metric (
    metric_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud       TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    namespace   TEXT NOT NULL,
    UNIQUE (cloud, metric_name, namespace)
);

-- date_key is the natural key YYYYMMDD, no identity needed
CREATE TABLE IF NOT EXISTS agentlens.dim_date (
    date_key  INTEGER PRIMARY KEY,
    full_date TEXT    NOT NULL,
    year      INTEGER NOT NULL,
    month     INTEGER NOT NULL,
    day       INTEGER NOT NULL
);

-- =====================================================================
-- Facts
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_consumption (
    agent_key  INTEGER          NOT NULL REFERENCES agentlens.dim_agent  (agent_key),
    metric_key INTEGER          NOT NULL REFERENCES agentlens.dim_metric (metric_key),
    model_key  INTEGER          NOT NULL REFERENCES agentlens.dim_model  (model_key),
    date_key   INTEGER          NOT NULL REFERENCES agentlens.dim_date   (date_key),
    ts         TEXT             NOT NULL,
    value      DOUBLE PRECISION,
    attributed SMALLINT         NOT NULL,
    PRIMARY KEY (agent_key, metric_key, model_key, ts)
);
CREATE INDEX IF NOT EXISTS idx_fact_consumption_date
    ON agentlens.fact_agent_consumption (date_key);
CREATE INDEX IF NOT EXISTS idx_fact_consumption_agent
    ON agentlens.fact_agent_consumption (agent_key);

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_snapshot (
    agent_key   INTEGER          NOT NULL REFERENCES agentlens.dim_agent  (agent_key),
    metric_key  INTEGER          NOT NULL REFERENCES agentlens.dim_metric (metric_key),
    date_key    INTEGER          NOT NULL REFERENCES agentlens.dim_date   (date_key),
    value_sum   DOUBLE PRECISION,
    value_count INTEGER,
    PRIMARY KEY (agent_key, metric_key, date_key)
);
CREATE INDEX IF NOT EXISTS idx_fact_snapshot_date
    ON agentlens.fact_agent_snapshot (date_key);

-- =====================================================================
-- Cost (FOCUS-lite) -- 2026-07-08
--
-- Decision: fact SEPARADO de fact_agent_consumption. Motivos:
--   * Grano distinto: coste es (recurso, meter, dia); consumo es
--     (agente, metrica, modelo, ts).
--   * Unidades distintas: mezclar moneda con tokens/llamadas en el mismo
--     ``value`` rompe la semantica de agregacion del snapshot.
--   * FOCUS aporta columnas (meter, subscription, resource_group) que se
--     perderian aplastandolas en la dim de metricas.
-- agent_key es NULLABLE: la atribucion recurso->agente llegara cuando
-- exista el mapeo (los native_agent_id del catalogo Agent 365 no son ARM
-- resource ids). Mientras, el coste queda a grano recurso, consultable
-- por dia/suscripcion/meter en Power BI.
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.fact_resource_cost (
    cloud             TEXT             NOT NULL,           -- 'azure' | 'aws'
    resource_id       TEXT             NOT NULL,
    date_key          INTEGER          NOT NULL REFERENCES agentlens.dim_date (date_key),
    meter_name        TEXT             NOT NULL DEFAULT '',
    billed_cost       DOUBLE PRECISION,
    effective_cost    DOUBLE PRECISION,
    consumed_quantity DOUBLE PRECISION,
    consumed_unit     TEXT,
    meter_category    TEXT,
    currency          TEXT,
    subscription_id   TEXT,
    resource_group    TEXT,
    agent_key         INTEGER          REFERENCES agentlens.dim_agent (agent_key),
    PRIMARY KEY (cloud, resource_id, date_key, meter_name)
);
CREATE INDEX IF NOT EXISTS idx_fact_resource_cost_date
    ON agentlens.fact_resource_cost (date_key);

-- =====================================================================
-- ETL bookkeeping -- 2026-07-08
--
-- Watermark de carga a nivel de fichero: build_star_pg.py salta los
-- parquets ya cargados (los upserts hacen que recargar sea inocuo pero
-- O(historico); con esto la carga es O(nuevo)). --full-scan lo ignora;
-- --rebuild lo trunca junto al resto.
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.etl_load_log (
    file_path TEXT        PRIMARY KEY,     -- relativo a raw root, separador '/'
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_count INTEGER
);

-- =====================================================================
-- Identity resolution + span grain + consumption tiers (ADR-010) -- 2026-07-09
--
-- ADR-010 "Attribution as Tiered Resolution": la atribucion agente<->consumo
-- se resuelve en la capa AgentLens con nivel de confianza explicito, sobre
-- grano span preservado. fact_agent_consumption pasa a rollup derivado.
--   * fact_agent_traces: landing a grano trace x span (topologia + caller +
--     content_ref). Sirve observabilidad y seguridad; los rollups derivan de el.
--   * bridge_agent_identity: mapeo cross-namespace otel_agent_id <-> packageId
--     M365 <-> agent ARN. Materializa la mapping table de ADR-003. NO se trunca
--     en --rebuild (dato curado); queda fuera de _ALL_TABLES en el loader.
--   * resolution_tier (native|bridge|correlation|unattributed): cada consumidor
--     filtra por confianza. Solo native+bridge son elegibles para chargeback.
--   * cost_basis (metered|allocated): nunca facturar coste repartido como medido.
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_traces (
    trace_id        TEXT        NOT NULL,
    span_id         TEXT        NOT NULL,
    parent_span_id  TEXT,
    agent_key       INTEGER     REFERENCES agentlens.dim_agent (agent_key),
    model_key       INTEGER     REFERENCES agentlens.dim_model (model_key),
    date_key        INTEGER     REFERENCES agentlens.dim_date  (date_key),
    ts              TIMESTAMPTZ NOT NULL,
    operation_name  TEXT,            -- invoke_agent | chat | execute_tool | create_agent | text_completion
    span_kind       TEXT,            -- agent_run | model_call | tool_call | retrieval
    native_agent_id TEXT,            -- gen_ai.agent.id tal cual en el span (puede ser NULL)
    caller_id       TEXT,            -- UserAuthenticatedId (best-effort; null-by-nature en runs programaticos)
    status          TEXT,
    duration_ms     DOUBLE PRECISION,
    input_tokens    INTEGER,
    output_tokens   INTEGER,
    total_tokens    INTEGER,
    tool_name       TEXT,
    content_ref     TEXT,            -- puntero a AppGenAIContent (dato gobernado), no el contenido
    resolution_tier TEXT        NOT NULL DEFAULT 'unattributed',
    PRIMARY KEY (trace_id, span_id)
);
CREATE INDEX IF NOT EXISTS idx_fact_traces_agent ON agentlens.fact_agent_traces (agent_key);
CREATE INDEX IF NOT EXISTS idx_fact_traces_date  ON agentlens.fact_agent_traces (date_key);

CREATE TABLE IF NOT EXISTS agentlens.bridge_agent_identity (
    agent_key    INTEGER     NOT NULL REFERENCES agentlens.dim_agent (agent_key) ON DELETE CASCADE,
    id_namespace TEXT        NOT NULL,     -- foundry_otel | m365_package | bedrock_arn
    native_id    TEXT        NOT NULL,     -- otel id base (version ':N' recortada) / packageId / ARN
    source       TEXT        NOT NULL,     -- curated_production | m365_registry | name_match_bulk
    confidence   TEXT        NOT NULL DEFAULT 'curated',   -- curated | name_match
    valid_from   TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to     TIMESTAMPTZ,
    PRIMARY KEY (id_namespace, native_id)
);

-- Columnas anadidas a tablas preexistentes (idempotente en DBs pobladas):
ALTER TABLE agentlens.fact_agent_consumption
    ADD COLUMN IF NOT EXISTS resolution_tier TEXT NOT NULL DEFAULT 'unattributed';
ALTER TABLE agentlens.fact_resource_cost
    ADD COLUMN IF NOT EXISTS cost_basis TEXT NOT NULL DEFAULT 'metered';

-- =====================================================================
-- Vistas de consumo (ADR-010) -- 2026-07-09
-- =====================================================================

-- FinOps: coste-por-agente por reparto de cuota de tokens (marcado allocated).
-- La rama 'unallocated' anade el remanente diario que ningun agente absorbe
-- (dias sin tokens atribuidos, o resto por redondeo): agent_key NULL y
-- cost_basis 'unallocated', de modo que la suma de la vista cuadra EXACTA
-- con fact_resource_cost. chargeback_eligible = solo tiers native/bridge.
CREATE OR REPLACE VIEW agentlens.v_finops_agent_cost AS
WITH agent_day AS (
    SELECT t.agent_key, t.date_key,
           SUM(COALESCE(t.total_tokens,0)) AS tokens,
           COUNT(*) FILTER (WHERE t.operation_name='invoke_agent') AS invocations,
           bool_or(t.resolution_tier IN ('native','bridge')) AS chargeback_eligible
    FROM agentlens.fact_agent_traces t
    WHERE t.resolution_tier <> 'unattributed'
    GROUP BY t.agent_key, t.date_key
),
day_tokens AS (SELECT date_key, SUM(tokens) AS total_tokens FROM agent_day GROUP BY date_key),
day_cost AS (
    SELECT date_key, SUM(COALESCE(effective_cost, billed_cost, 0)) AS cost, MAX(currency) AS currency
    FROM agentlens.fact_resource_cost GROUP BY date_key
),
allocated AS (
    SELECT ad.agent_key, a.agent_name, ad.date_key, ad.tokens, ad.invocations,
           ad.chargeback_eligible, dt.total_tokens, dc.cost AS day_resource_cost, dc.currency,
           CASE WHEN dt.total_tokens > 0
                THEN ROUND(((ad.tokens::numeric / dt.total_tokens) * COALESCE(dc.cost,0))::numeric, 6)
                ELSE 0 END AS allocated_cost,
           'allocated'::text AS cost_basis
    FROM agent_day ad
    JOIN agentlens.dim_agent a ON a.agent_key = ad.agent_key
    JOIN day_tokens dt ON dt.date_key = ad.date_key
    LEFT JOIN day_cost dc ON dc.date_key = ad.date_key
)
SELECT * FROM allocated
UNION ALL
SELECT NULL::int AS agent_key, '(unallocated)' AS agent_name, dc.date_key,
       NULL::bigint AS tokens, NULL::bigint AS invocations,
       false AS chargeback_eligible, NULL::bigint AS total_tokens,
       dc.cost AS day_resource_cost, dc.currency,
       ROUND((dc.cost - COALESCE(al.sum_alloc, 0))::numeric, 6) AS allocated_cost,
       'unallocated'::text AS cost_basis
FROM day_cost dc
LEFT JOIN (
    SELECT date_key, SUM(allocated_cost) AS sum_alloc FROM allocated GROUP BY date_key
) al USING (date_key)
WHERE dc.cost - COALESCE(al.sum_alloc, 0) > 0.0000005;

-- =====================================================================
-- Purview audit lens (ADR-005) -- 2026-07-09
--
-- fact_agent_audit: grano EVENTO del feed Audit.General (Purview / O365
-- Management Activity). Es el plano de gobierno/usuario del star:
--   * Join directo audit<->catalogo: TargetPlatformAgentId ('T_...'/'P_...')
--     ES el packageId de Agent 365 = dim_agent.native_agent_id (cloud m365).
--     Sin bridge. Ids no catalogados (BuiltIn_*, OutlookDraft, agentes
--     borrados) van al centinela con el id/nombre crudos preservados en el
--     fact -- son senal de gobierno, no error.
--   * El feed de audit NUNCA crea filas en dim_agent: el catalogo es SSoT.
--   * dim_user (UPN): dimension usuario. Purview es la fuente autoritativa
--     de caller (ADR-010 addendum); las trazas solo tienen best-effort.
--   * Campos de gobierno: DLPEvaluationDeferred, GuardrailDetails,
--     SensitivityLabelId, dlp_matches/sensitivity_labels (JSON crudo,
--     NULL cuando vacio para que el reporting filtre barato).
-- =====================================================================

CREATE TABLE IF NOT EXISTS agentlens.dim_user (
    user_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upn      TEXT NOT NULL,
    UNIQUE (upn)
);

CREATE TABLE IF NOT EXISTS agentlens.fact_agent_audit (
    record_id               TEXT        PRIMARY KEY,
    ts                      TIMESTAMPTZ NOT NULL,
    date_key                INTEGER     NOT NULL REFERENCES agentlens.dim_date  (date_key),
    agent_key               INTEGER     NOT NULL REFERENCES agentlens.dim_agent (agent_key),
    user_key                INTEGER     REFERENCES agentlens.dim_user (user_key),
    record_type             TEXT,       -- 261 CopilotInteraction | 407 InferenceCall | 334 | 363
    operation               TEXT,
    workload                TEXT,       -- Copilot | Agent365
    app_host                TEXT,       -- AppHost (261/334) o ChannelName (407)
    thread_id               TEXT,
    native_agent_id         TEXT,       -- TargetPlatformAgentId / AppIdentity crudo
    agent_name_raw          TEXT,       -- TargetAgentName tal cual en el evento
    platform_agent_type     TEXT,       -- InferenceCall: DeclarativeAgent | AzureAIFoundry
    error_type              TEXT,
    dlp_evaluation_deferred SMALLINT,
    dlp_matches             TEXT,       -- JSON; NULL cuando '[]'
    sensitivity_label_id    TEXT,
    sensitivity_labels      TEXT,       -- JSON; NULL cuando '[]'
    guardrail_details       TEXT,       -- JSON; NULL cuando '[]'
    resolution_tier         TEXT        NOT NULL DEFAULT 'unattributed'
);
CREATE INDEX IF NOT EXISTS idx_fact_audit_agent ON agentlens.fact_agent_audit (agent_key);
CREATE INDEX IF NOT EXISTS idx_fact_audit_date  ON agentlens.fact_agent_audit (date_key);
CREATE INDEX IF NOT EXISTS idx_fact_audit_user  ON agentlens.fact_agent_audit (user_key);

-- Seguridad: consumo sin atribuir = senal de gobierno (shadow / test / guid-only).
CREATE OR REPLACE VIEW agentlens.v_security_unregistered_consumption AS
SELECT split_part(COALESCE(t.native_agent_id,''), ':', 1) AS unresolved_agent_id,
       CASE
         WHEN t.native_agent_id IS NULL OR t.native_agent_id = '' THEN 'no_agent_id'
         WHEN t.native_agent_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-' THEN 'guid_only'
         ELSE 'named_unregistered'
       END AS signal_class,
       COUNT(*) AS spans, COUNT(DISTINCT t.trace_id) AS traces,
       SUM(COALESCE(t.total_tokens,0)) AS tokens,
       MIN(t.ts) AS first_seen, MAX(t.ts) AS last_seen
FROM agentlens.fact_agent_traces t
WHERE t.resolution_tier = 'unattributed'
GROUP BY 1, 2
ORDER BY tokens DESC;

-- =====================================================================
-- CAPA DE REPORTING (2026-07-10) -- contrato para Power BI
--
--   Vistas de solo lectura sobre el star; los facts no se tocan.
--   Diseno PBIX: importar v_cio_agent_scorecard como dimension agente
--   (excluye 'instructions' a proposito: tamano de modelo), dim_model,
--   dim_user y las vistas fact. Calendario DAX relacionado por
--   date_key (YYYYMMDD). Kit completo en agentlens/powerbi/.
--
--   * v_finops_cost_allocation: asignacion de coste por share de tokens
--     a grano (cloud, dia, agente, modelo). La cloud de matching es la
--     del MODELO (runtime que factura), NO la de dim_agent: el registro
--     Agent 365 es federado y los agentes Foundry viven como cloud
--     m365 en dim_agent. Linea 'unallocated' explicita por dia/cloud.
--   * v_usage_daily: audit Purview a grano (dia, agente, usuario,
--     record_type, tier). Proxy de uso M365 (getCopilotAgentUsage es
--     techo de plataforma).
--   * v_traces_daily: telemetria a grano (dia, agente, modelo, tier).
--     error_spans = status HTTP 4xx/5xx.
--   * v_finops_funnel_daily: funnel uso -> consumo -> coste por
--     (dia, cloud) para la pagina CFO.
--   * v_cio_agent_scorecard: 1 fila por agente de catalogo (excluye
--     centinelas) con redundancia (cluster por config_hash exacto),
--     uso (audit nativo + trazas native/bridge), coste asignado y tier
--     KEEP / REVIEW / DECOMMISSION_CANDIDATE. El tier es PROVISIONAL
--     mientras la ventana de audit sea corta (backfill Purview
--     pendiente, retencion 180 dias en Audit Standard).
--   * v_cio_dup_clusters: 1 fila por cluster de duplicados exactos.
-- =====================================================================

CREATE OR REPLACE VIEW agentlens.v_finops_cost_allocation AS
WITH grain AS (
    SELECT m.cloud,
           t.agent_key,
           t.model_key,
           t.date_key,
           sum(COALESCE(t.total_tokens, 0)) AS tokens,
           count(*) FILTER (WHERE t.operation_name = 'invoke_agent') AS invocations
    FROM agentlens.fact_agent_traces t
    JOIN agentlens.dim_model m ON m.model_key = t.model_key
    WHERE t.resolution_tier <> 'unattributed'
    GROUP BY m.cloud, t.agent_key, t.model_key, t.date_key
),
day_tokens AS (
    SELECT cloud, date_key, sum(tokens) AS total_tokens
    FROM grain
    GROUP BY cloud, date_key
),
day_cost AS (
    SELECT cloud, date_key,
           sum(COALESCE(effective_cost, billed_cost, 0)) AS cost,
           max(currency) AS currency
    FROM agentlens.fact_resource_cost
    GROUP BY cloud, date_key
),
allocated AS (
    SELECT g.cloud,
           g.date_key,
           g.agent_key,
           g.model_key,
           g.tokens,
           g.invocations,
           CASE WHEN dt.total_tokens > 0
                THEN round(((g.tokens::numeric / dt.total_tokens)::double precision * COALESCE(dc.cost, 0::double precision))::numeric, 6)
                ELSE 0::numeric
           END AS allocated_cost,
           dc.currency,
           'allocated'::text AS cost_basis
    FROM grain g
    JOIN day_tokens dt ON dt.cloud = g.cloud AND dt.date_key = g.date_key
    LEFT JOIN day_cost dc ON dc.cloud = g.cloud AND dc.date_key = g.date_key
)
SELECT cloud, date_key, agent_key, model_key, tokens, invocations,
       allocated_cost, currency, cost_basis
FROM allocated
UNION ALL
SELECT dc.cloud,
       dc.date_key,
       NULL::integer,
       NULL::integer,
       NULL::bigint,
       NULL::bigint,
       round((dc.cost - COALESCE(al.sum_alloc, 0::numeric)::double precision)::numeric, 6),
       dc.currency,
       'unallocated'::text
FROM day_cost dc
LEFT JOIN (
    SELECT cloud, date_key, sum(allocated_cost) AS sum_alloc
    FROM allocated
    GROUP BY cloud, date_key
) al ON al.cloud = dc.cloud AND al.date_key = dc.date_key
WHERE (dc.cost - COALESCE(al.sum_alloc, 0::numeric)::double precision) > 0.0000005::double precision;

CREATE OR REPLACE VIEW agentlens.v_usage_daily AS
SELECT date_key,
       agent_key,
       user_key,
       record_type,
       resolution_tier,
       count(*) AS events,
       count(*) FILTER (WHERE error_type IS NOT NULL AND error_type <> '') AS error_events,
       count(*) FILTER (WHERE dlp_evaluation_deferred = 1) AS dlp_deferred_events
FROM agentlens.fact_agent_audit
GROUP BY date_key, agent_key, user_key, record_type, resolution_tier;

CREATE OR REPLACE VIEW agentlens.v_traces_daily AS
SELECT t.date_key,
       t.agent_key,
       t.model_key,
       t.resolution_tier,
       count(*) AS spans,
       count(*) FILTER (WHERE t.operation_name = 'invoke_agent') AS invocations,
       count(*) FILTER (WHERE t.status ~ '^[45]') AS error_spans,
       sum(COALESCE(t.input_tokens, 0)) AS input_tokens,
       sum(COALESCE(t.output_tokens, 0)) AS output_tokens,
       sum(COALESCE(t.total_tokens, 0)) AS total_tokens,
       round(avg(t.duration_ms)::numeric, 2) AS avg_duration_ms
FROM agentlens.fact_agent_traces t
GROUP BY t.date_key, t.agent_key, t.model_key, t.resolution_tier;

CREATE OR REPLACE VIEW agentlens.v_finops_funnel_daily AS
WITH usage_d AS (
    SELECT date_key,
           'm365'::text AS cloud,
           count(*) AS audit_events,
           count(DISTINCT user_key) AS audit_users
    FROM agentlens.fact_agent_audit
    GROUP BY date_key
),
traces_d AS (
    SELECT t.date_key,
           a.cloud,
           count(*) FILTER (WHERE t.operation_name = 'invoke_agent') AS invocations,
           sum(COALESCE(t.total_tokens, 0)) AS tokens
    FROM agentlens.fact_agent_traces t
    JOIN agentlens.dim_agent a ON a.agent_key = t.agent_key
    GROUP BY t.date_key, a.cloud
),
cost_d AS (
    SELECT date_key,
           cloud,
           sum(COALESCE(effective_cost, billed_cost, 0)) AS resource_cost,
           max(currency) AS currency
    FROM agentlens.fact_resource_cost
    GROUP BY date_key, cloud
)
SELECT date_key,
       cloud,
       u.audit_events,
       u.audit_users,
       t.invocations,
       t.tokens,
       c.resource_cost,
       c.currency
FROM usage_d u
FULL JOIN traces_d t USING (date_key, cloud)
FULL JOIN cost_d c USING (date_key, cloud);

CREATE OR REPLACE VIEW agentlens.v_cio_agent_scorecard AS
WITH clusters AS (
    SELECT config_hash, count(*) AS cluster_size
    FROM agentlens.dim_agent
    WHERE config_hash IS NOT NULL AND config_hash <> ''
      AND native_agent_id <> '(unattributed)'
    GROUP BY config_hash
    HAVING count(*) > 1
),
audit_usage AS (
    SELECT agent_key,
           count(*) AS audit_events,
           count(DISTINCT user_key) AS distinct_users,
           max(ts) AS last_audit_ts
    FROM agentlens.fact_agent_audit
    WHERE resolution_tier = 'native'
    GROUP BY agent_key
),
trace_usage AS (
    SELECT agent_key,
           count(*) FILTER (WHERE operation_name = 'invoke_agent') AS invocations,
           sum(COALESCE(total_tokens, 0)) AS total_tokens,
           max(ts) AS last_trace_ts
    FROM agentlens.fact_agent_traces
    WHERE resolution_tier IN ('native', 'bridge')
    GROUP BY agent_key
),
alloc AS (
    SELECT agent_key, sum(allocated_cost) AS allocated_cost
    FROM agentlens.v_finops_cost_allocation
    WHERE cost_basis = 'allocated'
    GROUP BY agent_key
)
SELECT a.agent_key,
       a.cloud,
       a.native_agent_id,
       a.agent_name,
       a.agent_type,
       a.publisher,
       a.owner_id,
       a.status,
       a.enabled,
       a.config_hash,
       COALESCE(c.cluster_size, 1) AS cluster_size,
       (c.config_hash IS NOT NULL) AS in_dup_cluster,
       COALESCE(u.audit_events, 0) AS audit_events,
       COALESCE(u.distinct_users, 0) AS distinct_users,
       u.last_audit_ts,
       COALESCE(t.invocations, 0) AS invocations,
       COALESCE(t.total_tokens, 0) AS total_tokens,
       t.last_trace_ts,
       COALESCE(al.allocated_cost, 0) AS allocated_cost_eur,
       (u.agent_key IS NOT NULL OR t.agent_key IS NOT NULL) AS has_usage_signal,
       (COALESCE(u.distinct_users, 0) = 1) AS single_user,
       CASE
           WHEN u.agent_key IS NOT NULL OR t.agent_key IS NOT NULL THEN 'KEEP'
           WHEN c.config_hash IS NOT NULL THEN 'DECOMMISSION_CANDIDATE'
           ELSE 'REVIEW'
       END AS tier
FROM agentlens.dim_agent a
LEFT JOIN clusters c ON c.config_hash = a.config_hash
LEFT JOIN audit_usage u ON u.agent_key = a.agent_key
LEFT JOIN trace_usage t ON t.agent_key = a.agent_key
LEFT JOIN alloc al ON al.agent_key = a.agent_key
WHERE a.native_agent_id <> '(unattributed)';

CREATE OR REPLACE VIEW agentlens.v_cio_dup_clusters AS
SELECT s.config_hash,
       count(*) AS members,
       string_agg(DISTINCT s.agent_type, ', ') AS agent_types,
       min(s.agent_name) AS sample_name,
       count(*) FILTER (WHERE s.has_usage_signal) AS used_members,
       sum(s.audit_events) AS total_audit_events,
       sum(s.total_tokens) AS total_tokens,
       sum(s.allocated_cost_eur) AS allocated_cost_eur,
       left(max(a.instructions), 300) AS prompt_sample
FROM agentlens.v_cio_agent_scorecard s
JOIN agentlens.dim_agent a ON a.agent_key = s.agent_key
WHERE s.in_dup_cluster
GROUP BY s.config_hash;
